pluginManagement {
    repositories {
        google()
        mavenCentral()
    }
    plugins {
        id 'com.android.application'version '8.8.0' apply false
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } を追加してください。
    }
}
rootProject.name = "test"
include 'app'
