package android.content.pm;

import android.content.ComponentName;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.IBinder;
import android.os.Bundle;
import android.os.RemoteException;
import android.content.pm.PackageInfo;
import android.content.pm.ApplicationInfo;
import android.content.pm.ResolveInfo;
import android.content.pm.PermissionInfo;
import android.content.pm.PermissionGroupInfo;
import android.content.pm.ProviderInfo;
import android.content.pm.ServiceInfo;
import android.content.pm.ActivityInfo;
import android.content.pm.InstrumentationInfo;
import android.content.pm.FeatureInfo;
import android.content.pm.ParceledListSlice;
import android.content.pm.IPackageInstallObserver;
import android.content.pm.IPackageDeleteObserver;
import android.content.pm.IPackageDeleteObserver2;
import android.content.pm.IPackageDataObserver;
import android.content.pm.IPackageStatsObserver;
import android.content.pm.IPackageMoveObserver;
import android.content.pm.IPackageInstaller;
import android.content.pm.IPackageInstallerCallback;
import android.content.pm.dex.IArtManager;
import android.content.pm.KeySet;
import android.content.pm.ChangedPackages;
import android.content.pm.VersionedPackage;
import android.content.pm.PackageCleanItem;
import android.content.pm.VerifierDeviceIdentity;
import android.os.PersistableBundle;
import android.text.TextUtils;

interface IPackageManager {
    boolean isPackageAvailable(String packageName, int userId);
    PackageInfo getPackageInfo(String packageName, int flags, int userId);
    PackageInfo getPackageInfoVersioned(VersionedPackage versionedPackage, int flags, int userId);
    int getPackageUid(String packageName, int flags, int userId);
    int[] getPackageGids(String packageName, int flags, int userId);
    String[] currentToCanonicalPackageNames(String[] names);
    String[] canonicalToCurrentPackageNames(String[] names);
    PermissionInfo getPermissionInfo(String name, String packageName, int flags);
    ParceledListSlice queryPermissionsByGroup(String group, int flags);
    PermissionGroupInfo getPermissionGroupInfo(String name, int flags);
    ParceledListSlice getAllPermissionGroups(int flags);
    ApplicationInfo getApplicationInfo(String packageName, int flags, int userId);
    ActivityInfo getActivityInfo(ComponentName className, int flags, int userId);
    boolean activitySupportsIntent(ComponentName className, Intent intent, String resolvedType);
    ActivityInfo getReceiverInfo(ComponentName className, int flags, int userId);
    ServiceInfo getServiceInfo(ComponentName className, int flags, int userId);
    ProviderInfo getProviderInfo(ComponentName className, int flags, int userId);
    int checkPermission(String permName, String pkgName, int userId);
    int checkUidPermission(String permName, int uid);
    boolean addPermission(PermissionInfo info);
    void removePermission(String name);
    void grantRuntimePermission(String packageName, String permissionName, int userId);
    void revokeRuntimePermission(String packageName, String permissionName, int userId);
    void resetRuntimePermissions();
    int getPermissionFlags(String permissionName, String packageName, int userId);
    void updatePermissionFlags(String permissionName, String packageName, int flagMask, int flagValues, int userId);
    void updatePermissionFlagsForAllApps(int flagMask, int flagValues, int userId);
    boolean shouldShowRequestPermissionRationale(String permissionName, String packageName, int userId);
    boolean isProtectedBroadcast(String actionName);
    int checkSignatures(String pkg1, String pkg2);
    int checkUidSignatures(int uid1, int uid2);
    List<String> getAllPackages();
    String[] getPackagesForUid(int uid);
    String getNameForUid(int uid);
    String[] getNamesForUids(int[] uids);
    int getUidForSharedUser(String sharedUserName);
    int getFlagsForUid(int uid);
    int getPrivateFlagsForUid(int uid);
    boolean isUidPrivileged(int uid);
    String[] getAppOpPermissionPackages(String permissionName);
    ResolveInfo resolveIntent(Intent intent, String resolvedType, int flags, int userId);
    ResolveInfo findPersistentPreferredActivity(Intent intent, int userId);
    boolean canForwardTo(Intent intent, String resolvedType, int sourceUserId, int targetUserId);
    ParceledListSlice queryIntentActivities(Intent intent, String resolvedType, int flags, int userId);
    ParceledListSlice queryIntentActivityOptions(ComponentName caller, Intent[] specifics, String[] specificTypes, Intent intent, String resolvedType, int flags, int userId);
    ParceledListSlice queryIntentReceivers(Intent intent, String resolvedType, int flags, int userId);
    ResolveInfo resolveService(Intent intent, String resolvedType, int flags, int userId);
    ParceledListSlice queryIntentServices(Intent intent, String resolvedType, int flags, int userId);
    ParceledListSlice queryIntentContentProviders(Intent intent, String resolvedType, int flags, int userId);
    ParceledListSlice getInstalledPackages(int flags, int userId);
    ParceledListSlice getPackagesHoldingPermissions(String[] permissions, int flags, int userId);
    ParceledListSlice getInstalledApplications(int flags, int userId);
    ParceledListSlice getPersistentApplications(int flags);
    ProviderInfo resolveContentProvider(String name, int flags, int userId);
    void querySyncProviders(in List<String> outNames, in List<ProviderInfo> outInfo);
    ParceledListSlice queryContentProviders(String processName, int uid, int flags, String metaDataKey);
    InstrumentationInfo getInstrumentationInfo(ComponentName className, int flags);
    ParceledListSlice queryInstrumentation(String targetPackage, int flags);
    void finishPackageInstall(int token, boolean didLaunch);
    void setInstallerPackageName(String targetPackage, String installerPackageName);
    void setApplicationCategoryHint(String packageName, int categoryHint, String callerPackageName);
    void deletePackageAsUser(String packageName, int versionCode, IPackageDeleteObserver observer, int userId, int flags);
    void deletePackageVersioned(VersionedPackage versionedPackage, IPackageDeleteObserver2 observer, int userId, int flags);
    String getInstallerPackageName(String packageName);
    void resetApplicationPreferences(int userId);
    ResolveInfo getLastChosenActivity(Intent intent, String resolvedType, int flags);
    void setLastChosenActivity(Intent intent, String resolvedType, int flags, IntentFilter filter, int match, ComponentName activity);
    void addPreferredActivity(IntentFilter filter, int match, ComponentName[] set, ComponentName activity, int userId);
    void replacePreferredActivity(IntentFilter filter, int match, ComponentName[] set, ComponentName activity, int userId);
    void clearPackagePreferredActivities(String packageName);
    int getPreferredActivities(out List<IntentFilter> outFilters, out List<ComponentName> outActivities, String packageName);
    void addPersistentPreferredActivity(IntentFilter filter, ComponentName activity, int userId);
    void clearPackagePersistentPreferredActivities(String packageName, int userId);
    void addCrossProfileIntentFilter(IntentFilter intentFilter, String ownerPackage, int sourceUserId, int targetUserId, int flags);
    void clearCrossProfileIntentFilters(int sourceUserId, String ownerPackage);
    String[] setPackagesSuspendedAsUser(String[] packageNames, boolean suspended, PersistableBundle appExtras, PersistableBundle launcherExtras, String dialogMessage, String dialogMessageApp, int userId);
    boolean isPackageSuspendedForUser(String packageName, int userId);
    PersistableBundle getSuspendedPackageAppExtras(String packageName, int userId);
    byte[] getPreferredActivityBackup(int userId);
    void restorePreferredActivities(byte[] backup, int userId);
    byte[] getDefaultAppsBackup(int userId);
    void restoreDefaultApps(byte[] backup, int userId);
    byte[] getIntentFilterVerificationBackup(int userId);
    void restoreIntentFilterVerification(byte[] backup, int userId);
    byte[] getPermissionGrantBackup(int userId);
    void restorePermissionGrants(byte[] backup, int userId);
    ComponentName getHomeActivities(out List<ResolveInfo> outHomeCandidates);
    void setHomeActivity(ComponentName className, int userId);
    void setComponentEnabledSetting(ComponentName componentName, int newState, int flags, int userId);
    int getComponentEnabledSetting(ComponentName componentName, int userId);
    void setApplicationEnabledSetting(String packageName, int newState, int flags, int userId, String callingPackage);
    int getApplicationEnabledSetting(String packageName, int userId);
    void logAppProcessStartIfNeeded(String processName, int uid, String seinfo, String apkFile, int pid);
    void flushPackageRestrictionsAsUser(int userId);
    void setPackageStoppedState(String packageName, boolean stopped, int userId);
    void freeStorageAndNotify(String volumeUuid, long freeStorageSize, int storageFlags, IPackageDataObserver observer);
    void freeStorage(String volumeUuid, long freeStorageSize, int storageFlags, IntentSender pi);
    void deleteApplicationCacheFiles(String packageName, IPackageDataObserver observer);
    void deleteApplicationCacheFilesAsUser(String packageName, int userId, IPackageDataObserver observer);
    void clearApplicationUserData(String packageName, IPackageDataObserver observer, int userId);
    void clearApplicationProfileData(String packageName);
    void getPackageSizeInfo(String packageName, int userHandle, IPackageStatsObserver observer);
    String[] getSystemSharedLibraryNames();
    ParceledListSlice getSystemAvailableFeatures();
    boolean hasSystemFeature(String name, int version);
    void enterSafeMode();
    boolean isSafeMode();
    void systemReady();
    boolean hasSystemUidErrors();
    void performFstrimIfNeeded();
    void updatePackagesIfNeeded();
    void notifyPackageUse(String packageName, int reason);
    void notifyDexLoad(String loadingPackageName, List<String> classLoadersNames, List<String> classPaths, String loaderIsa);
    void registerDexModule(String packageName, String dexModulePath, boolean isModule, IDexModuleRegisterCallback callback);
    boolean performDexOptMode(String packageName, boolean checkProfiles, String compilerFilter, boolean force, boolean bootComplete, String splitName);
    boolean performDexOptSecondary(String packageName, String compilerFilter, boolean force);
    void dumpProfiles(String packageName);
    void forceDexOpt(String packageName);
    boolean runBackgroundDexoptJob(List<String> packageNames);
    void reconcileSecondaryDexFiles(String packageName);
    PackageCleanItem nextPackageToClean(PackageCleanItem lastPackage);
    int getMoveStatus(int moveId);
    void registerMoveCallback(IPackageMoveObserver callback);
    void unregisterMoveCallback(IPackageMoveObserver callback);
    int movePackage(String packageName, String volumeUuid);
    int movePrimaryStorage(String volumeUuid);
    boolean addPermissionAsync(PermissionInfo info);
    boolean setInstallLocation(int loc);
    int getInstallLocation();
    int installExistingPackageAsUser(String packageName, int userId, int installFlags, int installReason);
    void verifyPendingInstall(int id, int verificationCode);
    void extendVerificationTimeout(int id, int verificationCodeAtTimeout, long millisecondsToDelay);
    void verifyIntentFilter(int id, int verificationCode, List<String> failedDomains);
    int getIntentVerificationStatus(String packageName, int userId);
    boolean updateIntentVerificationStatus(String packageName, int status, int userId);
    ParceledListSlice getIntentFilterVerifications(String packageName);
    ParceledListSlice getAllIntentFilters(String packageName);
    boolean setDefaultBrowserPackageName(String packageName, int userId);
    String getDefaultBrowserPackageName(int userId);
    VerifierDeviceIdentity getVerifierDeviceIdentity();
    boolean isFirstBoot();
    boolean isOnlyCoreApps();
    boolean isUpgrade();
    void setPermissionEnforced(String permission, boolean enforced);
    boolean isPermissionEnforced(String permission);
    boolean isStorageLow();
    boolean setApplicationHiddenSettingAsUser(String packageName, boolean hidden, int userId);
    boolean getApplicationHiddenSettingAsUser(String packageName, int userId);
    void setSystemAppHiddenUntilInstalled(String packageName, boolean hidden);
    boolean setSystemAppInstallState(String packageName, boolean installed, int userId);
    IPackageInstaller getPackageInstaller();
    boolean setBlockUninstallForUser(String packageName, boolean blockUninstall, int userId);
    boolean getBlockUninstallForUser(String packageName, int userId);
    KeySet getKeySetByAlias(String packageName, String alias);
    KeySet getSigningKeySet(String packageName);
    boolean isPackageSignedByKeySet(String packageName, KeySet ks);
    boolean isPackageSignedByKeySetExactly(String packageName, KeySet ks);
    void addOnPermissionsChangeListener(IOnPermissionsChangeListener listener);
    void removeOnPermissionsChangeListener(IOnPermissionsChangeListener listener);
    void grantDefaultPermissionsToEnabledCarrierApps(String[] packageNames, int userId);
    void grantDefaultPermissionsToEnabledImsServices(String[] packageNames, int userId);
    void grantDefaultPermissionsToEnabledTelephonyDataServices(String[] packageNames, int userId);
    void revokeDefaultPermissionsFromDisabledTelephonyDataServices(String[] packageNames, int userId);
    void grantDefaultPermissionsToActiveLuiApp(String packageName, int userId);
    void revokeDefaultPermissionsFromLuiApps(String[] packageNames, int userId);
    boolean isPermissionRevokedByPolicy(String permission, String packageName, int userId);
    String getPermissionControllerPackageName();
    ParceledListSlice getInstantApps(int userId);
    byte[] getInstantAppCookie(String packageName, int userId);
    boolean setInstantAppCookie(String packageName, byte[] cookie, int userId);
    Bitmap getInstantAppIcon(String packageName, int userId);
    boolean isInstantApp(String packageName, int userId);
    boolean setRequiredForSystemUser(String packageName, boolean required);
    void setUpdateAvailable(String packageName, boolean updateAvailable);
    String getServicesSystemSharedLibraryPackageName();
    String getSharedSystemSharedLibraryPackageName();
    ChangedPackages getChangedPackages(int sequenceNumber, int userId);
    boolean isPackageDeviceAdminOnAnyUser(String packageName);
    int getInstallReason(String packageName, int userId);
    ParceledListSlice getSharedLibraries(String packageName, int flags, int userId);
    boolean canRequestPackageInstalls(String packageName, int userId);
    void deletePreloadsFileCache();
    ComponentName getInstantAppResolverComponent();
    ComponentName getInstantAppResolverSettingsComponent();
    ComponentName getInstantAppInstallerComponent();
    String getInstantAppAndroidId(String packageName, int userId);
    IArtManager getArtManager();
    void setHarmfulAppWarning(String packageName, CharSequence warning, int userId);
    CharSequence getHarmfulAppWarning(String packageName, int userId);
    boolean hasSigningCertificate(String packageName, byte[] signingCertificate, int flags);
    boolean hasUidSigningCertificate(int uid, byte[] signingCertificate, int flags);
    String getSystemTextClassifierPackageName();
    boolean isPackageStateProtected(String packageName, int userId);
}
